JWT_SECRET_KEY: "abcdexgh"
JWT_TOKEN_EXPIRE_TIME: "5"
MONGODB_CONNECTION_URI: "mongodb://localhost:27017/"
MONGODB_DATABASE_NAME: "expense_manager"
MYSQL_CONNECTION_STRING: "root:@localhost:3306/expense_manager"